n_gpu: 1
arch:
  type: 'EverythingAtOnceModel'
  args:
    video_embed_dim: 4096
    text_embed_dim: 300
    davenet_v2: true
    strategy_audio_pooling: 'none'
    token_projection: 'gated'
    use_positional_emb: false
    individual_projections: true
    fusion_params:
      embed_dim: 4096
      use_cls_token: false
      depth: 1
      num_heads: 64
      mlp_ratio: 1
    projection_dim: 6144
    projection: 'gated'

data_loader:
  type: FeatureDataloader
  args:
    num_workers: 4
    batch_size: 16
    shuffle: false
    drop_last: true
    dataset_name: 'SoundActions'
    dataset_kwargs:
      word2vec_path: '/fp/homes01/u01/ec-jinyueg/felles/Research/Users/jinyueg/SoundAction/everything_at_once/data/GoogleNews/GoogleNews-vectors-negative300.bin'
      video_feature_path: '/fp/homes01/u01/ec-jinyueg/felles/Research/Users/jinyueg/SoundAction/everything_at_once/data/SoundActions/video_features'
      audio_feature_path: '/fp/homes01/u01/ec-jinyueg/felles/Research/Users/jinyueg/SoundAction/everything_at_once/data/SoundActions/audio_features'
      use_2D: true
      use_3D: false
      debug: true

optimizer:
  type: Adam
  args:
    lr: 0.00005
lr_scheduler:
  type: ExponentialLR
  args:
    gamma: 0.9

loss:
  type: CombinatorialLoss
  args:
    tv_weight: 1
    ta_weight: 0.1
    va_weight: 0.1
    t_va_weight: 0.1
    v_ta_weight: 0.1
    a_tv_weight: 0.1

metrics:
- t2v_metrics
- v2t_metrics
- t2a_metrics
- a2t_metrics
- v2a_metrics
- a2v_metrics
- t2va_metrics
- va2t_metrics
- v2ta_metrics
- ta2v_metrics
- a2tv_metrics
- tv2a_metrics
- t2v+a_metrics
- v+a2t_metrics
- v2t+a_metrics
- t+a2v_metrics
- a2t+v_metrics
- t+v2a_metrics
trainer:
  epochs: 15
  mixed_precision: true
#  max_samples_per_epoch: 1000 #  for debug
  save_dir: ./output
  save_period: 20
  verbosity: 2
  monitor: 'off'
  init_val: false
  neptune: false
